#! /bin/sh
bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width		2
bspc config window_gap			4
bspc config single_monocle		false
bspc config click_to_focus		false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config split_ratio          	0.52
bspc config paddingless_monocle		true

bspc config normal_border_color         "#B3BDCB"
bspc config focused_border_color        "#5294E2"
bspc config presel_feedback_color         "#CC575D"

bspc rule -a MEGAsync state=floating
bspc rule -a Skype state=floating
bspc rule -a Safeeyes state=floating manage=off
bspc rule -a Variety state=floating
bspc rule -a Gpick state=floating
bspc rule -a VirtualBox Manager state=floating
bspc rule -a Software-properties-gtk state=floating
bspc rule -a Gnome-calendar state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Hamster state=floating
bspc rule -a Orage state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Screenkey manage=off

bspc rule -a firefox desktop='2'
bspc rule -a Brave-browser desktop='2'
bspc rule -a LibreWolf desktop='2'
bspc rule -a qutebrowser desktop='2'
bspc rule -a Code desktop='3'
bspc rule -a jetbrains-studio desktop='3'
bspc rule -a obs desktop='4'
bspc rule -a Rambox desktop='5'
bspc rule -a TelegramDesktop desktop='5'
bspc rule -a Signal desktop='5'

# Auto starts
bsp-layout set tall &
pgrep -x sxhkd > /dev/null || sxhkd > /dev/null 2>&1 &
"$HOME"/.config/polybar/load.sh
pgerp -x picom > /dev/null || picom -f -D 4 > /dev/null 2>&1 &
setxkbmap -layout us,ir &
setxkbmap -option 'grp:alt_shift_toggle' &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgerp -x conky > /dev/null || conky > /dev/null 2>&1 &
pgrep -x redshift > /dev/null || redshift -c ~/.config/redshift/redshift.conf > /dev/null 2>&1 &
nm-applet &
blueman-applet &
variety &
safeeyes &
syncthing &
kdeconnect-indicator &
optimus-manager-qt &
feh --bg-fill --randomize /mnt/1TB/Pictures/Wallpaper.repo/* &
