#!/usr/bin/env bash
bookmarks=()
bookmarks+=("/home/mhmd")
bookmarks+=("/home/mhmd/Pictures")
bookmarks+=("/mnt/1TB/Pictures")
bookmarks+=("/mnt/1TB/Pictures/Wallpaper.repo")

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read -r file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

while read -r file
do
	case "$1" in
	"C-d") rm "$file" ;;
	"C-r") telegram-upload "$file" --to https://t.me/joinchat/T2V_vUfpFbQfXFde --caption "" &
	  	notify-send "Telegram-upload" "  File uploaded to telegram";;
	"C-g") tr '\n' '\0' | xargs -0 gimp & ;;
	"C-w") feh --bg-scale "$file"
	  	notify-send "  Wallpaper chaneged" ;;
	"C-m") 
		path=$(printf '%s\n' "${bookmarks[@]}" | dmenu -p "Enter move path: ") 2> /dev/null
		if [[ -n "$path" ]]; then
		  mv "$file" "$path"
		fi
	  ;;
	"C-comma")  rotate 270 ;;
	"C-period") rotate  90 ;;
	"C-slash")  rotate 180 ;;
	esac
done
